name: Update README with GitHub Stats

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install PyGithub

      - name: Generate stats
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }} # PAT com limites maiores
        run: python scripts/stats.py > stats.md

      - name: Update README
        run: |
          # Cria backup do README original
          cp README.md README.backup

          # Insere as stats entre os marcadores
          awk '
          BEGIN {p=1} 
          /<!--START_SECTION:stats-->/ {print; system("cat stats.md"); p=0; next} 
          /<!--END_SECTION:stats-->/ {p=1} 
          p==1 {print}' README.backup > README.md

          # Remove o backup
          rm README.backup

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          # Verifica se há mudanças antes de commitar
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "📊 Update stats [skip ci]"
            git push
          fi
